version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    # volumes:
    #   - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  