version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: timurmb/devops_project1_dev
    ## check build+image condition here: 
    ## https://docs.docker.com/compose/compose-file/compose-file-v3/#image
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - ./tests:/app/tests
      - ./Makefile:/app/Makefile
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    container_name: app_dev 

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      # - $PWD/site:/srv
      # - caddy_data:/data
      # - caddy_config:/config
    container_name: caddy_dev 
    depends_on:
      - app
