version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: timurmb/devops_project1_dev
    ## check build+image condition here: 
    ## https://docs.docker.com/compose/compose-file/compose-file-v3/#image
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - ./tests:/app/tests
      - ./Makefile:/app/Makefile
    env_file:
      - .env    

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
