version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "8080:8080"
    # volumes:
    #   - ./app:/root/app
    #   - ./tests:/root/app/tests
    #   - ./Makefile:/root/app/Makefile

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      # - $PWD/site:/srv
      # - caddy_data:/data
      # - caddy_config:/config
    depends_on:
      - app
