version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: nodos server -h 0.0.0.0
    ports:
      - "8080:8080"

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
      # - $PWD/site:/srv
      # - caddy_data:/data
      # - caddy_config:/config
    depends_on:
      - app
