version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: timurmb/devops_project1:latest
    ## check build+image condition here: 
    ## https://docs.docker.com/compose/compose-file/compose-file-v3/#image
    command: make test
    # environment:
    #   - DATABASE_HOST=${DATABASE_HOST}
    #   - DATABASE_NAME=${DATABASE_NAME}
    #   - DATABASE_USERNAME=${DATABASE_USERNAME}
    #   - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
