# [docker build] + [docker push] + test
name: build

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: test
        run: make ci
        # env:
        #   DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        #   DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        #   DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        #   DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.production
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops_project1:latest
